modes=[ "pusher", "syncer" ]

# 检查文件变动间隔（秒）
interval = 1

[local]
path = "xxxx"

[remote]
path = "xxxx"


[pusher]
oss-provider = "qiniu"
oss-object-prefix = "prefix"

[oss-qiniu]
bucket = "xxx"
access-key = "xxx"
sercet-key = "xxx"
